name: Simple Workflow

on:
  workflow_dispatch:  # Permite ejecutar el workflow manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Saludo
      run: echo "Hola, Bienvenido al workflow"

    - name: Simular instalación
      run: |
        echo "Instalando dependencias..."
        sleep 20  # Simula un proceso de instalación

    - name: Simular limpieza de basura
      run: |
        echo "Limpieza de archivos temporales..."
        sleep 10  # Simula un proceso de limpieza

    - name: Despedida
      run: echo "Adiós, el workflow ha terminado"
